### ISSUE TITLE
java.lang.OutOfMemoryError: Java heap space

### ISSUE THREAD

**Issue by dzenanz** [gabysbrain/tuner#25]
Trying to import samples, this error occurs during "Building GP" step. I have plenty of memory (32GB), but I don't know how to increase the size available to tuner. The file I am currently trying to import has 15625 samples.

**Comment by gabysbrain** [comment]
Sorry for the late response. The problem is that the way we're building the GP model is not really designed to handle that many points. To determine the correlation parameters the model building process needs to create a matrix of the correlation between all the sample points and then invert it. So in your case the matrix would be 15625x15625 and be quite large. We're looking into alternatives when given a large number of sample points (large being more than 500) but I haven't had a chance to implement anything yet.
